// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfs4RtKzPJrqrvnBOP5On-26az1PX8hPY',
    appId: '1:1053095993905:web:ba2ab6684a9a7d8c316b10',
    messagingSenderId: '1053095993905',
    projectId: 'flutterfirebase-94aa4',
    authDomain: 'flutterfirebase-94aa4.firebaseapp.com',
    storageBucket: 'flutterfirebase-94aa4.appspot.com',
    measurementId: 'G-1EDV30YVKL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkVVYrIJVzdj4o9rFLZcXTeKfQos_bW0U',
    appId: '1:1053095993905:android:ce3b0ef66c224ae0316b10',
    messagingSenderId: '1053095993905',
    projectId: 'flutterfirebase-94aa4',
    storageBucket: 'flutterfirebase-94aa4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6TKTN2dgzj5pNcUsFn9Rt_NuOVTpgf3k',
    appId: '1:1053095993905:ios:92fdbdd21c14ba3b316b10',
    messagingSenderId: '1053095993905',
    projectId: 'flutterfirebase-94aa4',
    storageBucket: 'flutterfirebase-94aa4.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6TKTN2dgzj5pNcUsFn9Rt_NuOVTpgf3k',
    appId: '1:1053095993905:ios:92fdbdd21c14ba3b316b10',
    messagingSenderId: '1053095993905',
    projectId: 'flutterfirebase-94aa4',
    storageBucket: 'flutterfirebase-94aa4.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfs4RtKzPJrqrvnBOP5On-26az1PX8hPY',
    appId: '1:1053095993905:web:37cdc0f1382e51ee316b10',
    messagingSenderId: '1053095993905',
    projectId: 'flutterfirebase-94aa4',
    authDomain: 'flutterfirebase-94aa4.firebaseapp.com',
    storageBucket: 'flutterfirebase-94aa4.appspot.com',
    measurementId: 'G-Q7QRK3MGLW',
  );
}
